import { v4 as uuid } from 'uuid'

import SocialMediaPost from 'interfaces/SocialMediaPost'

export const sampleSocialMediaPostsData: SocialMediaPost[] = [
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [
      {
        type: 'video',
        url: 'https://dafftube.org/wp-content/uploads/2014/01/Sample_1280x720_mp4.mp4',
      },
    ],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'youtube',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
  {
    id: uuid(),
    title: 'Some Twitter Post',
    body: "It's here! The #GuardiansoftheGalaxyHolidaySpecial is now streaming on Disney+🎄 Our VFX superheroes had a blast adding some holiday sparkle to this festive firecracker 🎁 #GotGHolidaySpecial",
    createdDate: new Date(),
    origin: 'twitter',
    media: [],
  },
]
